apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jest-test
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to Jest
      type: string
      default: "-v"
  steps:
    - name: jest
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        echo "Running Jest with args: $(params.args)"
        npx jest $(params.args)
